export const ordersList: GlobalProps['orders'] = [
    {
        id: '1',
        shipid: '107713',
        date: '3rd January, 2023',
        status: 'successful',
        customer: 'Racheal Adeyemi',
        email: 'rachealadeyemi.net@gmail.com',
        country: 'Nigeria',
        shipping: 'Australian Post Api',
        source: 'shopifyBU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '2',
        shipid: '107713',
        date: '15th January, 2023',
        status: 'incomplete',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '3',
        shipid: '107713',
        date: '20th January, 2023',
        status: 'successful',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '4',
        shipid: '107713',
        date: '3rd January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '5',
        shipid: '107713',
        date: '15th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '6',
        shipid: '107713',
        date: '20th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '7',
        shipid: '107713',
        date: '3rd January, 2023',
        status: 'incomplete',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '8',
        shipid: '107713',
        date: '15th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '9',
        shipid: '107719',
        date: '20th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '10',
        shipid: '107710',
        date: '20th January, 2023',
        status: 'successful',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '11',
        shipid: '107713',
        date: '3rd January, 2023',
        status: 'successful',
        customer: 'Racheal Adeyemi',
        email: 'rachealadeyemi.net@gmail.com',
        country: 'Nigeria',
        shipping: 'Australian Post Api',
        source: 'shopifyBU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '12',
        shipid: '107713',
        date: '15th January, 2023',
        status: 'incomplete',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '13',
        shipid: '107713',
        date: '20th January, 2023',
        status: 'successful',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '14',
        shipid: '107713',
        date: '3rd January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '15',
        shipid: '107713',
        date: '15th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '16',
        shipid: '107713',
        date: '20th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '17',
        shipid: '107713',
        date: '3rd January, 2023',
        status: 'incomplete',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '18',
        shipid: '107713',
        date: '15th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '19',
        shipid: '107719',
        date: '20th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '20',
        shipid: '107710',
        date: '20th January, 2023',
        status: 'successful',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '21',
        shipid: '107713',
        date: '3rd January, 2023',
        status: 'successful',
        customer: 'Racheal Adeyemi',
        email: 'rachealadeyemi.net@gmail.com',
        country: 'Nigeria',
        shipping: 'Australian Post Api',
        source: 'shopifyBU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '22',
        shipid: '107713',
        date: '15th January, 2023',
        status: 'incomplete',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '23',
        shipid: '107713',
        date: '20th January, 2023',
        status: 'successful',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '24',
        shipid: '107713',
        date: '3rd January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '25',
        shipid: '107713',
        date: '15th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '26',
        shipid: '107713',
        date: '20th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '27',
        shipid: '107713',
        date: '3rd January, 2023',
        status: 'incomplete',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '28',
        shipid: '107713',
        date: '15th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '29',
        shipid: '107719',
        date: '20th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '30',
        shipid: '107710',
        date: '20th January, 2023',
        status: 'successful',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '31',
        shipid: '107713',
        date: '3rd January, 2023',
        status: 'successful',
        customer: 'Racheal Adeyemi',
        email: 'rachealadeyemi.net@gmail.com',
        country: 'Nigeria',
        shipping: 'Australian Post Api',
        source: 'shopifyBU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '32',
        shipid: '107713',
        date: '15th January, 2023',
        status: 'incomplete',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '33',
        shipid: '107713',
        date: '20th January, 2023',
        status: 'successful',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '34',
        shipid: '107713',
        date: '3rd January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '35',
        shipid: '107713',
        date: '15th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '36',
        shipid: '107713',
        date: '20th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '37',
        shipid: '107713',
        date: '3rd January, 2023',
        status: 'incomplete',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '38',
        shipid: '107713',
        date: '15th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '39',
        shipid: '107719',
        date: '20th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '40',
        shipid: '107710',
        date: '20th January, 2023',
        status: 'successful',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
]