export const ordersList: GlobalProps['orders'] = [
    {
        id: '1',
        shipid: '107713',
        date: '3rd January, 2023',
        status: 'successful',
        customer: 'Racheal Adeyemi',
        email: 'rachealadeyemi.net@gmail.com',
        country: 'Nigeria',
        shipping: 'Australian Post Api',
        source: 'shopifyBU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '2',
        shipid: '107713',
        date: '15th January, 2023',
        status: 'incomplete',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '3',
        shipid: '107713',
        date: '20th January, 2023',
        status: 'successful',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '4',
        shipid: '107713',
        date: '3rd January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '5',
        shipid: '107713',
        date: '15th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '6',
        shipid: '107713',
        date: '20th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '7',
        shipid: '107713',
        date: '3rd January, 2023',
        status: 'incomplete',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '8',
        shipid: '107713',
        date: '15th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '9',
        shipid: '107719',
        date: '20th January, 2023',
        status: 'pending',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
    {
        id: '10',
        shipid: '107710',
        date: '20th January, 2023',
        status: 'successful',
        customer: 'Ahmed',
        email: 'armed@gmail.com',
        country: 'Australia',
        shipping: 'shopifyAU',
        source: 'shopifyAU',
        orderType: 'customer',
        isChecked: false
    },
]